# Default values for arm64v8-bitcoind
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

terminationGracePeriodSeconds: 300

image:
  repository: jkaldon/arm64v8-bitcoind
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "22.0.0-12"
  lifecycle:
    preStop:
      exec:
        command: ["/usr/local/bin/bitcoin-cli", "stop"]

#initEnv:
#- name: RPC_USERNAME
#  value: admin
#- name: RPC_PASSWORD
#  value: your_secret_password

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim:
  ## jenkins data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: nfs-client
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  volumes:
  - name: bitcoin-data
    persistentVolumeClaim:
      claimName: bitcoind
  mounts:
  - name: bitcoin-data
    mountPath: /data
    readOnly: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  ports:
    - port: 8332
      targetPort: 8332
      protocol: TCP
      name: rpc
    - port: 8333
      targetPort: 8333
      protocol: TCP
      name: p2p
    - port: 28332
      targetPort: 28332
      protocol: TCP
      name: rpc-zmq
    - port: 28333
      targetPort: 28333
      protocol: TCP
      name: p2p-zmq
